// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmTym8j70erNJJaUSdhKowIPvfCaKG94U',
    appId: '1:711355003769:web:628d02cbe05be3aea1f5a8',
    messagingSenderId: '711355003769',
    projectId: 'bloodsearch-becb4',
    authDomain: 'bloodsearch-becb4.firebaseapp.com',
    storageBucket: 'bloodsearch-becb4.appspot.com',
    measurementId: 'G-0YJ59T0LQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmLNbb5JLnrOMFYPVsV4cU0o_7NXf_GU',
    appId: '1:711355003769:android:199b8b2d3a5ee02ba1f5a8',
    messagingSenderId: '711355003769',
    projectId: 'bloodsearch-becb4',
    storageBucket: 'bloodsearch-becb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC14VcgFkFrTLTleHyArJ6sX6HONIPmyZE',
    appId: '1:711355003769:ios:1d93e2352a556e20a1f5a8',
    messagingSenderId: '711355003769',
    projectId: 'bloodsearch-becb4',
    storageBucket: 'bloodsearch-becb4.appspot.com',
    iosBundleId: 'com.example.donneursang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC14VcgFkFrTLTleHyArJ6sX6HONIPmyZE',
    appId: '1:711355003769:ios:60e568a01ddbbce7a1f5a8',
    messagingSenderId: '711355003769',
    projectId: 'bloodsearch-becb4',
    storageBucket: 'bloodsearch-becb4.appspot.com',
    iosBundleId: 'com.example.donneursang.RunnerTests',
  );
}
