// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvs8OgbIWT0GjlY9_-V-rqDRGBriBgW-w',
    appId: '1:503142718676:web:2b9133c0334f8d2efe2f41',
    messagingSenderId: '503142718676',
    projectId: 'blood-donnation',
    authDomain: 'blood-donnation.firebaseapp.com',
    storageBucket: 'blood-donnation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ATvJQCDeOT-gWeGK18qnngma3f1j_2M',
    appId: '1:503142718676:android:b8a2c14f79f0313ffe2f41',
    messagingSenderId: '503142718676',
    projectId: 'blood-donnation',
    storageBucket: 'blood-donnation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuhJh5QVI1iSCFctMcYJIjEvu2Iooz3gA',
    appId: '1:503142718676:ios:c732ccede28f0977fe2f41',
    messagingSenderId: '503142718676',
    projectId: 'blood-donnation',
    storageBucket: 'blood-donnation.appspot.com',
    iosBundleId: 'com.example.donneursang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuhJh5QVI1iSCFctMcYJIjEvu2Iooz3gA',
    appId: '1:503142718676:ios:2a1963aed6643980fe2f41',
    messagingSenderId: '503142718676',
    projectId: 'blood-donnation',
    storageBucket: 'blood-donnation.appspot.com',
    iosBundleId: 'com.example.donneursang.RunnerTests',
  );
}
